version: 2
enable-beta-ecosystems: true
updates:
  # uv
  - package-ecosystem: "uv"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
  # yarn
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "yarn prod"
      include: "scope"
  # GH actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
