# This allows to run the playground with a pre-populated MongoDB backend
version: '3'
services:
  mongodb:
    image: mongo:5
    ports:
      # Forwarding port to host in case we want to manually run requests against mongo
      - 27017:27017
    volumes:
      - ./playground/init-mongo/:/docker-entrypoint-initdb.d/:ro
      - ./playground/datastore/:/datasources/:ro
    environment:
      MONGO_INITDB_DATABASE: "playground_data"

  weaverbird:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb:27017"
      MONGODB_DATABASE_NAME: "playground_data"
