repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: system
    name: Lint with Ruff
    entry: ruff
    types: [python]
    language: system

  - id: system
    name: Lint with Black
    entry: black
    types: [python]
    language: system

  - id: system
    name: Lint with Mypy
    # shitty, but commands are always ran from the repo root: https://github.com/pre-commit/pre-commit/issues/1110
    entry: bash -c 'cd server && mypy'
    types: [python]
    language: system
    exclude: ^tests/
