source "https://rubygems.org"
ruby RUBY_VERSION

gem "github-pages"

# Plugins (should already be included by GitHub pages):
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jekyll-seo-tag"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
